### ISSUE TITLE
Settings are not populated back to the form and get lost

### ISSUE THREAD

**Issue by sascha-egerer** [n3v3rf411/jenkins-auth-phabricator#1]
If i configure the plugin everything works fine but after the "save" the fields are empty. If i then save the settings again all settings are lost as they are overwritten with empty values.

**Comment by n3v3rf411** [comment]
I'm aware of this (and continuously ignoring because we rarely open the configuration page anyway). I'll try to fix this in the next two weeks. This is probably just due to incorrect use of Jenkins plugins API.
